name: "Devs For Change, Inc"
locales: [en]
domains: [devsforchange.org]
timezone: UTC
seo_title: "Devs For Change, Inc"
meta_keywords:
meta_description:
metafields:
  core:
    twitter_feed: https://twitter.com
    twitter_link: https://twitter.com
    facebook_link: https://facebook.com
metafields_ui: {}
